# Generated by Django 4.1.7 on 2023-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('case_name', models.CharField(default='', max_length=20)),
                ('disease', models.BigIntegerField(default=1)),
                ('patient_specie', models.CharField(default='', max_length=20)),
                ('patient_age', models.IntegerField(default=1)),
                ('patient_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission', models.CharField(default='', max_length=20)),
                ('admission_pic', models.CharField(default='', max_length=20)),
                ('admission_video', models.CharField(default='', max_length=20)),
                ('checking', models.CharField(default='', max_length=20)),
                ('checking_pic', models.CharField(default='', max_length=20)),
                ('checking_video', models.CharField(default='', max_length=20)),
                ('diagnostic_result', models.CharField(default='', max_length=20)),
                ('treatment', models.CharField(default='', max_length=20)),
                ('treatment_pic', models.CharField(default='', max_length=20)),
                ('treatment_video', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='', max_length=20)),
                ('manager', models.CharField(default='', max_length=20)),
                ('introduction', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('permission', models.BigIntegerField(default=1)),
            ],
        ),
    ]
