# Generated by Django 4.1 on 2023-04-26 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='', max_length=20)),
                ('manager', models.CharField(default='', max_length=20)),
                ('introduction', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('disease_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=20)),
                ('category', models.TextField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='disposition',
            fields=[
                ('disposition_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('disposition_name', models.CharField(max_length=20)),
                ('disposition_price', models.IntegerField(default=0)),
                ('introduction', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('paper_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=20)),
                ('creator_id', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('project_price', models.IntegerField(default=0)),
                ('introduction', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('answer', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.disease')),
            ],
        ),
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('qp_id', models.CharField(default=0, max_length=8, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(default=0, max_length=8)),
                ('question_id', models.CharField(default=0, max_length=8)),
                ('question_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='question_type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('result_id', models.IntegerField(primary_key=20, serialize=False)),
                ('user_id', models.IntegerField()),
                ('result_answer', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.question_type'),
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.question')),
            ],
        ),
        migrations.CreateModel(
            name='exam_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.result')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('starting_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('excellent_score', models.IntegerField()),
                ('passing_score', models.IntegerField()),
                ('candidate', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.paper')),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('case_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('case_name', models.CharField(default='', max_length=20)),
                ('patient_specie', models.CharField(default='', max_length=20)),
                ('patient_age', models.IntegerField(default=1)),
                ('patient_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission', models.CharField(default='', max_length=20)),
                ('admission_pic', models.CharField(default='', max_length=20)),
                ('admission_video', models.CharField(default='', max_length=20)),
                ('checking', models.CharField(default='', max_length=20)),
                ('checking_pic', models.CharField(default='', max_length=20)),
                ('checking_video', models.CharField(default='', max_length=20)),
                ('diagnostic_result', models.CharField(default='', max_length=20)),
                ('treatment', models.CharField(default='', max_length=20)),
                ('treatment_pic', models.CharField(default='', max_length=20)),
                ('treatment_video', models.CharField(default='', max_length=20)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.disease')),
            ],
        ),
    ]
