# Generated by Django 4.1 on 2023-04-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question_paper',
        ),
    ]
