# Generated by Django 4.1.7 on 2023-03-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='introduction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='disposition',
            fields=[
                ('disposition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disposition_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=100)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department')),
            ],
        ),
    ]
