# Generated by Django 4.1 on 2023-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_question_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('qp_id', models.CharField(default=0, max_length=8, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(default=0, max_length=8)),
                ('question_id', models.CharField(default=0, max_length=8)),
                ('question_number', models.IntegerField()),
            ],
        ),
    ]
