# Generated by Django 4.1.7 on 2023-03-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('disease_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.disease'),
        ),
    ]
