# Generated by Django 4.1 on 2023-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_question_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='creator',
            field=models.TextField(default='unknown'),
        ),
    ]
