# Generated by Django 4.1.7 on 2023-03-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_question_question_type_test_paper_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='paper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.test_paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_paper',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.question'),
            preserve_default=False,
        ),
    ]
