# Generated by Django 4.1 on 2023-04-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_paper_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.question'),
        ),
    ]
