# Generated by Django 4.1 on 2023-04-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_question_paper_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.paper'),
        ),
    ]
