# Generated by Django 4.1.7 on 2023-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_exam_paper_id_test_paper_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='candidate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
