# Generated by Django 4.1 on 2023-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_question_paper_paper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='admission_pic',
        ),
        migrations.RemoveField(
            model_name='case',
            name='admission_video',
        ),
        migrations.RemoveField(
            model_name='case',
            name='checking_pic',
        ),
        migrations.RemoveField(
            model_name='case',
            name='checking_video',
        ),
        migrations.RemoveField(
            model_name='case',
            name='treatment_pic',
        ),
        migrations.RemoveField(
            model_name='case',
            name='treatment_video',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
