# Generated by Django 4.1 on 2023-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_disposition_belong_to_remove_disposition_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('project_price', models.IntegerField(default=0)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='introduction',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(default='', max_length=20),
        ),
    ]
