# Generated by Django 4.1 on 2023-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_disease_category_alter_disease_disease_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
