# Generated by Django 4.1 on 2023-04-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_disposition_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_paper',
            name='question_id',
        ),
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.test_paper')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.question')),
            ],
        ),
    ]
